version: 2
updates:
  - directory: "/"
    package-ecosystem: "github-actions"
    schedule:
      interval: "weekly"
      timezone: "Europe/Paris"
    commit-message:
      prefix: "chore(ci)"

  - directory: "/"
    package-ecosystem: "npm"
    schedule:
      interval: "weekly"
      timezone: "Europe/Paris"
    commit-message:
      prefix: "chore(deps)"
