version: 2
updates:
  - directory: "/"
    package-ecosystem: "github-actions"
    schedule:
      interval: "daily"
      timezone: "Europe/Paris"
    commit-message:
      prefix: "ci"

  - directory: "/dagger"
    package-ecosystem: "gomod"
    schedule:
      interval: "daily"
      timezone: "Europe/Paris"
    commit-message:
      prefix: "ci"

  - directory: "/"
    package-ecosystem: "npm"
    schedule:
      interval: "daily"
      timezone: "Europe/Paris"
    commit-message:
      prefix: "chore"
