name: "The name of your action here"
description: "Provide a description here"
author: "Your name or organization here"

# Define your inputs here.
inputs:
  cloud-token:
    description: "Your input description here"
    required: false

runs:
  using: node20
  main: dist/main/index.js
  post: dist/post/index.js
