name: "Stale"

on:
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: "${{ github.workflow }}"
  cancel-in-progress: true

jobs:
  stale:
    name: "Stale issues and pull requests"
    runs-on: "ubuntu-22.04"

    permissions:
      contents: "write"
      issues: "write"
      pull-requests: "write"

    steps:
      - name: "Mark and close"
        id: "stale"
        uses: "actions/stale@v9"
        with:
          stale-pr-message: "Is it still relevant?"
          close-pr-message: "No activity, closing."
          days-before-stale: 30
          days-before-close: 7
          delete-branch: true
